fix for macos

diff --git a/update b/update
--- a/update
+++ b/update
@@ -1,10 +1,13 @@
 #!/usr/bin/env bash
-cd "$(dirname "$(readlink -f "$0")")" || (echo "cd into dotfile directory failed"; exit)
+cd "$(dirname "$(stat -f "$0")")" || (echo "cd into dotfile directory failed"; exit)
 git pull
-list=$(find `ls | sed -e 's/^update$//'` -type f)
+list=$(find `/bin/ls | sed -e 's/^update$//'` -type f)
 dir="$(pwd)"
-cd || echo "filed to cd into home directory"
+cd || (echo "failed to cd into home directory"; exit)
 for i in $list; do
+    if [[ -f ".$i.OLD" ]]; then
+        rm ".$i.OLD"
+    fi
     if [[ -f ".$i" ]]; then
         mv ".$i" ".$i.OLD"
     fi
@@ -18,6 +21,11 @@ done
 #git clone git@github.com:xayon40-12/.doom.d
 #cd ~/.doom.d && git pull && ~/.doom.d/install
 cd ~/.config || (echo "cd into ~/.config failed"; exit)
-git clone git@github.com:xayon40-12/nvim
-cd ~/.config/nvim || (echo "cd into ~/.config/nvim failed"; exit)
-./install
+if [[ ! -d nvim/ ]]; then
+  git clone git@github.com:xayon40-12/nvim
+  cd ~/.config/nvim || (echo "cd into ~/.config/nvim failed"; exit)
+  ./install
+else
+  cd ~/.config/nvim || (echo "cd into ~/.config/nvim failed"; exit)
+  git pull
+fi
